### Get all transactions
GET https://pos-transaction-web-app.onrender.com/transactions

###

### Create a transaction
POST https://pos-transaction-web-app.onrender.com/auth/login
Content-Type: application/json

{
  "product": "Bread",
  "quantity": 2,
  "price": 800
}